Repository team-dododok/honeypot-fe, pull requests merged in 2024-12, with the labels that each got.

#42 [Feat] 그룹 내부 편지 이미지 저장 및 삭제 경고 반영
  src/api/auth/postReissue.ts
  src/api/authAxios.tsx
  src/features/Badge/components/Badge.tsx
  src/features/Compliment/components/Modal/DetailHoneyModal.tsx
  src/features/Compliment/components/Modal/HoneyMoveCheckModal.tsx
  src/features/Compliment/components/Modal/HoneyMoveModal.tsx
  src/features/Group/components/Modal/CreateGroupModal.tsx
  src/features/Group/components/Modal/EditGroupNameModal.tsx
  src/features/Group/components/Modal/GroupModal.tsx
  src/hooks/receivedPraise/useDeleteReceivedPraise.ts
  src/pages/GuidePage.tsx
  src/pages/badge/BadgePage.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/compliment/send/ComplimentSendContentPage.tsx
  src/pages/compliment/send/ComplimentSendTargetPage.tsx
  src/pages/group/GroupDetailPage.tsx
  src/pages/profile/EmailUpdatePage.tsx
  src/pages/profile/ProfileUpdatePage.tsx
  src/pages/signup/SignUpEmailPage.tsx
  src/pages/signup/SignUpNamePage.tsx
  src/utils/saveImage.ts
Labels: :bug: fix, ✨ feat

#43 [Design] 1차 QA
  src/features/Group/components/Modal/CreateGroupModal.tsx
  src/features/Main/components/GroupList.tsx
  src/features/Main/components/GroupPagination.tsx
  src/features/Main/components/HoneyGroup.tsx
  src/features/Main/components/MainBottomSheet.tsx
  src/hooks/group/usePostGroup.ts
  src/pages/profile/ProfileUpdatePage.tsx
Labels: :lipstick: design

#44 [Feat] 로그인 안 됐을 때 이동하는 페이지
  src/routes/index.tsx
Labels: ✨ feat

#45 [Fix] 그룹명 수정 오류
  src/features/Group/components/Modal/EditGroupNameModal.tsx
  src/hooks/group/usePatchGroup.ts
  src/pages/group/GroupDetailPage.tsx
Labels: :bug: fix

#46 [Fix] 1차 QA
  public/assets/images/compliment/bongbong-complete.svg
  src/components/Input/Input.tsx
  src/components/Input/LinedInput.tsx
  src/features/Compliment/components/Letter/ComplimentLetter.tsx
  src/features/Compliment/components/Letter/Letter.tsx
  src/features/Group/components/Modal/EditGroupNameModal.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/compliment/send/ComplimentSendCompletePage.tsx
  src/pages/group/GroupDetailPage.tsx
  src/pages/signup/SignUpEmailPage.tsx
  src/styles/GlobalStyle.tsx
  src/types/components/InputProps.tsx
  src/utils/saveImage.ts
Labels: :bug: fix

#48 [Feat] 그룹 내부 > 그룹 삭제 API 연동
  src/features/Group/components/Modal/EditGroupNameModal.tsx
Labels: ✨ feat

#49 [Fix] 이메일 인증시간 5분으로 변경
  src/pages/signup/SignUpEmailPage.tsx
Labels: :bug: fix

#50 [Feat] 꿀 옮기기 그룹 정보 조회 및 카카오 공유 콜백 기능 추가
  src/api/group/getGroupMember.ts
  src/api/group/types/Group.ts
  src/api/sendPraise/getSendCheck.ts
  src/features/Compliment/components/Modal/HoneyMoveCheckModal.tsx
  src/hooks/group/useGroupMember.ts
  src/hooks/sendPraise/usePostSendPraise.ts
  src/hooks/sendPraise/useSendCheck.ts
  src/pages/compliment/send/ComplimentSendContentPage.tsx
Labels: ✨ feat

#52 [Fix] 2차 QA 추가
  src/components/Modal/BottomModal.tsx
  src/features/Main/components/HoneyBlank.tsx
  src/features/Main/components/MainBottomSheet.tsx
  src/features/Profile/components/Profile.tsx
  src/pages/profile/EmailUpdatePage.tsx
Labels: :bug: fix

#53 [Design] QA 수정사항 UI 관련 내용 반영
  src/components/Sidebar/MenuSection.tsx
  src/components/Sidebar/SidebarMenu.tsx
  src/constants/menu.ts
  src/features/Group/components/Modal/GroupModal.tsx
  src/hooks/group/usePostGroup.ts
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/profile/ProfileUpdatePage.tsx
  src/styles/GlobalStyle.tsx
  src/types/constants/MenuItem.tsx
Labels: :lipstick: design

#55 [Design] QA 외 수정사항 반영
  package-lock.json
  package.json
  src/api/sendPraise/getSendCheck.ts
  src/api/sendPraise/types/SendPraise.ts
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Input/Input.tsx
  src/components/Modal/BottomModal.tsx
  src/components/Modal/CenterModal.tsx
  src/features/Compliment/components/KakaoPreview.tsx
  src/features/Compliment/components/Modal/HoneyMoveCheckModal.tsx
  src/features/Compliment/components/Modal/InfoModal.tsx
  src/features/Compliment/components/Modal/PreviewModal.tsx
  src/features/Group/components/Container/GroupTabContainer.tsx
  src/features/Stamp/components/Modal/StampModal.tsx
  src/hooks/sendPraise/useSendCheck.ts
  src/pages/GuidePage.tsx
  src/pages/MainPage.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/compliment/send/ComplimentSendContentPage.tsx
  src/pages/group/GroupDetailPage.tsx
  src/pages/signup/SignUpEmailPage.tsx
  src/styles/GlobalStyle.tsx
  src/types/components/InputProps.tsx
  yarn.lock
Labels: :lipstick: design

#56 [Feat] 로그아웃 API 연동 및 uuid 경로 오류 수정
  src/api/auth/postLogout.ts
  src/components/Sidebar/SidebarMenu.tsx
  src/pages/compliment/send/ComplimentSendContentPage.tsx
Labels: :bug: fix, ✨ feat

#57 [Fix] 카카오 공유하기 확인 API 요청 url 형식 수정
  src/api/sendPraise/getSendCheck.ts
Labels: :bug: fix

#60 [Fix] 2차 QA
  src/components/Button/BackButton.tsx
  src/components/Button/Button.tsx
  src/components/Header/BackHeader.tsx
  src/components/Header/Header.tsx
  src/constants/menu.ts
  src/features/Group/components/Modal/EditGroupNameModal.tsx
  src/features/Main/components/HoneyGroup.tsx
  src/features/Profile/components/Profile.tsx
  src/features/Stamp/components/Stamp/StampCard.tsx
  src/layouts/SubLayout.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/compliment/send/ComplimentSendTargetPage.tsx
  src/pages/group/GroupDetailPage.tsx
  src/routes/index.tsx
Labels: :bug: fix

#61 [Feat] BestStamp tooltip
  src/features/Profile/components/Profile.tsx
  src/features/Profile/constants/profile.ts
  yarn.lock
Labels: ✨ feat

#62 [Fix] 3차 QA
  package.json
  src/features/Compliment/components/Letter/ComplimentLetter.tsx
  src/features/Compliment/components/Letter/ReadLetter.tsx
  src/features/Stamp/components/Stamp/HoneyStamp.tsx
  src/features/Stamp/components/Stamp/StampCard.tsx
  src/features/Stamp/components/Stamp/StampLabel.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/utils/saveImage.ts
  src/utils/storage.ts
  vite.config.ts
Labels: :bug: fix

#63 [Feat] 꿀 저장하기 및 보낸 꿀 삭제 안내 토스트 등
  public/assets/images/profile/profile-1.svg
  public/assets/images/profile/profile-2.svg
  public/assets/images/profile/profile-3.svg
  public/assets/images/profile/profile-4.svg
  public/assets/images/profile/profile-5.svg
  public/assets/images/profile/profile-6.svg
  src/components/Button/Button.tsx
  src/features/Compliment/components/Modal/DetailHoneyModal.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/compliment/send/ComplimentSendTargetPage.tsx
  src/pages/group/GroupDetailPage.tsx
Labels: ✨ feat

#64 [Fix] 경고모달과 봉봉이 손 z-index 오류 수정
  src/pages/group/GroupDetailPage.tsx
Labels: :bug: fix

#65 [Fix] 4차 QA 수정
  public/assets/images/profile/profile-1.svg
  public/assets/images/profile/profile-2.svg
  public/assets/images/profile/profile-3.svg
  public/assets/images/profile/profile-4.svg
  public/assets/images/profile/profile-5.svg
  public/assets/images/profile/profile-6.svg
  public/assets/images/stamp/stamp-select.svg
  src/api/receivedPraise/types/ReceivedPraise.ts
  src/components/Button/Button.tsx
  src/features/Compliment/components/Letter/ComplimentLetter.tsx
  src/features/Compliment/components/Letter/ReadLetter.tsx
  src/features/Stamp/components/Stamp/HoneyStamp.tsx
  src/features/Stamp/components/Stamp/StampLabel.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/compliment/send/ComplimentSendContentPage.tsx
Labels: :bug: fix, :lipstick: design

#66 [Design] 텍스트 및 경로 이동 수정
  src/features/Stamp/components/Modal/StampModal.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/group/GroupDetailPage.tsx
Labels: :lipstick: design

#67 [File] 꿀도장 선택 이미지 파일 수정
  public/assets/images/stamp/stamp-select-default.svg
  src/features/Compliment/components/Letter/ComplimentLetter.tsx
Labels: 📁 file

#68 [Fix] 그룹명 변경 오류 해결 및 텍스트 수정
  src/features/Group/components/Modal/EditGroupNameModal.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/pages/compliment/send/ComplimentSendTargetPage.tsx
  src/pages/group/GroupDetailPage.tsx
Labels: :bug: fix

#69 [Fix] 이메일 disabled 오류 수정
  src/pages/signup/SignUpEmailPage.tsx
Labels: :bug: fix

#70 [Design] 스크롤 등 UI 관련 개선사항
  src/components/Input/LinedInput.tsx
  src/components/Sidebar/SidebarMenu.tsx
  src/features/Compliment/components/Letter/Letter.tsx
  src/features/Main/components/MainBottomSheet.tsx
  src/layouts/YellowBackgroundLayout.tsx
  src/pages/announcement/AnnouncementPage.tsx
  src/pages/compliment/ComplimentDetailPage.tsx
  src/styles/GlobalStyle.tsx
Labels: :lipstick: design

#71 [Design] 받은 편지 조회 페이지 하단 margin 추가
  src/pages/compliment/ComplimentDetailPage.tsx
Labels: :lipstick: design
